# Generated by Django 5.1.6 on 2025-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_photos/%y/%m/%d')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
