# Generated by Django 5.1.6 on 2025-04-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_category_name'),
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
