# Generated by Django 5.1.6 on 2025-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='isAdmin',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
