# Generated by Django 5.1.6 on 2025-03-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_admin_isadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
