# Generated by Django 5.1.6 on 2025-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0003_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=100)),
                ('image3', models.CharField(max_length=100)),
                ('image4', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
