# Generated by Django 5.1.6 on 2025-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
