# Generated by Django 5.1.6 on 2025-04-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_products_image1_alter_products_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('nameFr', models.CharField(max_length=50)),
                ('nameAr', models.CharField(max_length=50)),
            ],
        ),
    ]
