# Generated by Django 5.1.6 on 2025-04-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_dashboard.category'),
        ),
    ]
