# Generated by Django 5.1.6 on 2025-05-04 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='startedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
